name: ac-bench-ffi
maintainer: Channable
category: Other
synopsis: Benchmark code for alfred-margaret
description: Benchmark code for alfred-margaret
version: '0'
github: channable/alfred-margaret

extra-source-files:
- package.yaml

library: {}

dependencies:
- base

ghc-options: >-
  -Wall
  -Wincomplete-record-updates
  -Wincomplete-uni-patterns
  -Wpartial-fields
  -j4
  +RTS -A64m -RTS

executables:
  ac-bench-ffi:
    dependencies:
    - alfred-margaret
    - base
    - bytestring
    - clock
    - ghc-compact
    - deepseq
    - primitive
    - text
    ghc-options:
    - -rtsopts
    - -threaded
    - '"-with-rtsopts=-I0 -T -N -A32m -n4m -qg"'
    main: Main.hs
    source-dirs: app/
    extra-libraries:
    - libacbench
    extra-lib-dirs:
    - libacbench/target/release